name             'myproject'
maintainer       'YOUR_COMPANY_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures myproject'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'

#depends 'apt'
depends 'build-essential'
depends 'chef_handler'
depends 'git'
#depends 'dmg'
#depends 'vim'
depends 'runit'
depends 'python'
#depends 'yum'
#depends 'yum-epel'
